# ADP CLI Auto-Initialization Script
# Unified installation using APPDATA with launcher script approach

param(
    [string]$InstallScriptUrl = "https://raw.githubusercontent.com/Laiye-ADP/adp-cli/master/scripts/install_test.ps1"
)

# Set UTF-8 encoding
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
[Console]::InputEncoding = [System.Text.Encoding]::UTF8
$OutputEncoding = [System.Text.Encoding]::UTF8
$env:PYTHONIOENCODING = "utf-8"

# Configuration
$AppName = "adp"
$CompanyName = "Laiye-ADP"
$InstallRoot = Join-Path $env:APPDATA $CompanyName
$AdpInstallDir = Join-Path $InstallRoot "adp-cli"
$AdpBinDir = Join-Path $AdpInstallDir "bin"
$LauncherDir = Join-Path $env:USERPROFILE ".local\bin"  # Preferred user-level bin directory

# Alternative launcher directories (in order of preference)
$PossibleLauncherDirs = @(
    "$env:USERPROFILE\.local\bin",           # Modern Unix-like convention
    "$env:USERPROFILE\bin",                   # Simple user bin
    "$env:APPDATA\Microsoft\Windows\Start Menu\Programs"  # Start menu (for .bat files)
)

# Function to find a directory already in PATH
function Find-WritablePathDirectory {
    $pathDirs = $env:PATH -split ';'
    
    foreach ($dir in $pathDirs) {
        # Check if directory exists and is writable
        if (Test-Path $dir) {
            try {
                # Test write permission
                $testFile = Join-Path $dir ".adp_test_write_$(Get-Random)"
                New-Item -Path $testFile -ItemType File -Force -ErrorAction Stop | Out-Null
                Remove-Item $testFile -Force -ErrorAction SilentlyContinue
                
                Write-Host "  ✓ Found writable PATH directory: $dir" -ForegroundColor Green
                return $dir
            }
            catch {
                # Directory not writable, continue
                Write-Host "  ⚠️  Directory in PATH but not writable: $dir" -ForegroundColor Gray
            }
        }
    }
    
    return $null
}

# Function to create launcher script (batch file)
function New-LauncherScript {
    param(
        [string]$LauncherDir,
        [string]$TargetExe,
        [string]$CommandName
    )
    
    # Create batch file launcher
    $batchPath = Join-Path $LauncherDir "$CommandName.bat"
    $batchContent = @"
@echo off
REM Launcher for ADP CLI
REM Auto-generated by ADP installer

set "ADP_HOME=$AdpInstallDir"
"$TargetExe" %*
"@
    
    Set-Content -Path $batchPath -Value $batchContent -Encoding ASCII
    Write-Host "  ✓ Created batch launcher: $batchPath" -ForegroundColor Green
    
    # Also create PowerShell wrapper (optional, for better integration)
    $psPath = Join-Path $LauncherDir "$CommandName.ps1"
    $psContent = @"
# PowerShell wrapper for ADP CLI
# Auto-generated by ADP installer

`$script:ADP_HOME = "$AdpInstallDir"
& "$TargetExe" @args
"@
    
    Set-Content -Path $psPath -Value $psContent -Encoding UTF8
    Write-Host "  ✓ Created PowerShell wrapper: $psPath" -ForegroundColor Green
    
    return $batchPath
}

# Function to add directory to user PATH
function Add-ToUserPath {
    param([string]$NewPath)
    
    $currentUserPath = [Environment]::GetEnvironmentVariable("PATH", "User")
    
    # Normalize paths for comparison
    $normalizedNewPath = [System.IO.Path]::GetFullPath($NewPath.TrimEnd('\'))
    $pathItems = $currentUserPath -split ';' | Where-Object { $_ -ne '' }
    
    $exists = $false
    foreach ($item in $pathItems) {
        try {
            $normalizedItem = [System.IO.Path]::GetFullPath($item.TrimEnd('\'))
            if ($normalizedItem -eq $normalizedNewPath) {
                $exists = $true
                break
            }
        }
        catch {
            # Skip invalid paths
        }
    }
    
    if (-not $exists) {
        $updatedPath = if ($currentUserPath) { "$currentUserPath;$NewPath" } else { $NewPath }
        [Environment]::SetEnvironmentVariable("PATH", $updatedPath, "User")
        Write-Host "  ✓ Added to user PATH: $NewPath" -ForegroundColor Green
        return $true
    }
    
    Write-Host "  ✓ Already in user PATH: $NewPath" -ForegroundColor Cyan
    return $false
}

# Enhanced Python detection
function Find-Python {
    # Try PATH first
    $pythonCmd = Get-Command python, python3 -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($pythonCmd) {
        return $pythonCmd
    }
    
    # Try Windows Registry
    $regPaths = @(
        "HKLM:\SOFTWARE\Python\PythonCore\*\InstallPath",
        "HKCU:\SOFTWARE\Python\PythonCore\*\InstallPath"
    )
    
    foreach ($regPath in $regPaths) {
        $pythonInstalls = Get-ItemProperty -Path $regPath -ErrorAction SilentlyContinue
        foreach ($install in $pythonInstalls) {
            $pythonExe = Join-Path $install."(default)" "python.exe"
            if (Test-Path $pythonExe) {
                return Get-Command $pythonExe
            }
        }
    }
    
    # Try common locations
    $commonPaths = @(
        "$env:LOCALAPPDATA\Programs\Python\Python*",
        "C:\Python*",
        "C:\Program Files\Python*"
    )
    
    foreach ($pattern in $commonPaths) {
        $pythonDirs = Get-ChildItem -Path $pattern -Directory -ErrorAction SilentlyContinue |
                      Where-Object { $_.Name -match 'Python3[0-9]+' } |
                      Sort-Object Name -Descending
        foreach ($dir in $pythonDirs) {
            $pythonExe = Join-Path $dir.FullName "python.exe"
            if (Test-Path $pythonExe) {
                return Get-Command $pythonExe
            }
        }
    }
    
    return $null
}

# Function to install ADP CLI using pip
function Install-ADPCLI {
    param([string]$PythonExe)
    
    Write-Host "  Installing ADP CLI using pip..." -ForegroundColor Yellow
    
    # Ensure pip is available
    $pipCmd = "$PythonExe -m pip"
    
    # Try to install/upgrade ADP CLI
    $installResult = & $pipCmd install --upgrade adp-cli 2>&1
    
    if ($LASTEXITCODE -ne 0) {
        Write-Host "  ❌ Pip installation failed" -ForegroundColor Red
        Write-Host "  Error: $installResult" -ForegroundColor Red
        return $false
    }
    
    Write-Host "  ✓ ADP CLI installed successfully" -ForegroundColor Green
    return $true
}

# Function to find installed ADP CLI executable
function Find-ADPExe {
    # First check if already installed in our unified directory
    $localExe = Join-Path $AdpBinDir "adp.exe"
    if (Test-Path $localExe) {
        return $localExe
    }
    
    # Check Python Scripts directory
    $pythonCmd = Find-Python
    if ($pythonCmd) {
        $pythonDir = Split-Path $pythonCmd.Source -Parent
        $scriptsDir = Join-Path $pythonDir "Scripts"
        $pythonExe = Join-Path $scriptsDir "adp.exe"
        if (Test-Path $pythonExe) {
            return $pythonExe
        }
    }
    
    # Check PATH
    $pathExe = Get-Command adp -ErrorAction SilentlyContinue
    if ($pathExe) {
        return $pathExe.Source
    }
    
    return $null
}

# Main execution
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "   ADP CLI Unified Installer" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Step 1: Create installation directories
Write-Host "📁 Setting up installation directories..." -ForegroundColor Yellow

if (-not (Test-Path $AdpInstallDir)) {
    New-Item -Path $AdpInstallDir -ItemType Directory -Force | Out-Null
    Write-Host "  ✓ Created: $AdpInstallDir" -ForegroundColor Green
}

if (-not (Test-Path $AdpBinDir)) {
    New-Item -Path $AdpBinDir -ItemType Directory -Force | Out-Null
    Write-Host "  ✓ Created: $AdpBinDir" -ForegroundColor Green
}

Write-Host ""

# Step 2: Find or install ADP CLI
Write-Host "🔍 Checking ADP CLI installation..." -ForegroundColor Yellow

$existingAdp = Find-ADPExe

if ($existingAdp -and (Test-Path $existingAdp)) {
    Write-Host "  ✓ ADP CLI already exists: $existingAdp" -ForegroundColor Green
    
    # Copy to unified directory if not already there
    if ($existingAdp -ne (Join-Path $AdpBinDir "adp.exe")) {
        Copy-Item -Path $existingAdp -Destination $AdpBinDir -Force
        Write-Host "  ✓ Copied to unified directory: $AdpBinDir" -ForegroundColor Green
    }
} else {
    Write-Host "  ⚠️  ADP CLI not found, installing..." -ForegroundColor Yellow
    
    # Find Python
    $pythonCmd = Find-Python
    if (-not $pythonCmd) {
        Write-Host "  ❌ Python not found! Cannot install ADP CLI" -ForegroundColor Red
        Write-Host "  Please install Python 3.8+ from: https://www.python.org/downloads/" -ForegroundColor Yellow
        exit 1
    }
    
    Write-Host "  ✓ Using Python: $($pythonCmd.Source)" -ForegroundColor Green
    
    # Install using pip
    if (Install-ADPCLI -PythonExe $pythonCmd.Source) {
        # Find where pip installed adp.exe
        $pythonDir = Split-Path $pythonCmd.Source -Parent
        $scriptsDir = Join-Path $pythonDir "Scripts"
        $pipInstalledExe = Join-Path $scriptsDir "adp.exe"
        
        if (Test-Path $pipInstalledExe) {
            Copy-Item -Path $pipInstalledExe -Destination $AdpBinDir -Force
            Write-Host "  ✓ Copied to unified directory: $AdpBinDir" -ForegroundColor Green
        } else {
            Write-Host "  ⚠️  Could not locate installed adp.exe" -ForegroundColor Yellow
        }
    } else {
        Write-Host "  ❌ Installation failed" -ForegroundColor Red
        exit 1
    }
}

Write-Host ""

# Step 3: Create launcher in writable PATH directory
Write-Host "🔧 Creating command launcher..." -ForegroundColor Yellow

$targetExe = Join-Path $AdpBinDir "adp.exe"

if (-not (Test-Path $targetExe)) {
    Write-Host "  ❌ Target executable not found: $targetExe" -ForegroundColor Red
    exit 1
}

# Strategy 1: Try to find an existing writable PATH directory
$writablePathDir = Find-WritablePathDirectory

if ($writablePathDir) {
    # Create launcher directly in existing PATH directory
    $launcherPath = New-LauncherScript -LauncherDir $writablePathDir -TargetExe $targetExe -CommandName "adp"
    Write-Host "  ✓ Launcher created in existing PATH directory" -ForegroundColor Green
} 
else {
    # Strategy 2: Try to add our preferred launcher directory to PATH
    Write-Host "  No writable PATH directory found, will add new directory..." -ForegroundColor Yellow
    
    $launcherDirCreated = $false
    foreach ($candidateDir in $PossibleLauncherDirs) {
        if (-not (Test-Path $candidateDir)) {
            try {
                New-Item -Path $candidateDir -ItemType Directory -Force | Out-Null
                Write-Host "  ✓ Created directory: $candidateDir" -ForegroundColor Green
            }
            catch {
                continue
            }
        }
        
        # Test if we can write to this directory
        try {
            $testFile = Join-Path $candidateDir ".adp_test_write_$(Get-Random)"
            New-Item -Path $testFile -ItemType File -Force -ErrorAction Stop | Out-Null
            Remove-Item $testFile -Force -ErrorAction SilentlyContinue
            
            # Create launcher here
            $launcherPath = New-LauncherScript -LauncherDir $candidateDir -TargetExe $targetExe -CommandName "adp"
            Write-Host "  ✓ Launcher created in: $candidateDir" -ForegroundColor Green
            
            # Add this directory to user PATH
            Add-ToUserPath -NewPath $candidateDir
            $launcherDirCreated = $true
            break
        }
        catch {
            Write-Host "  ⚠️  Cannot write to: $candidateDir" -ForegroundColor Gray
        }
    }
    
    if (-not $launcherDirCreated) {
        Write-Host "  ❌ Failed to create launcher in any directory" -ForegroundColor Red
        Write-Host "  Please manually add to PATH: $AdpBinDir" -ForegroundColor Yellow
    }
}

Write-Host ""

# Step 4: Update current session PATH
Write-Host "🔄 Updating current session..." -ForegroundColor Yellow

# Add launcher directory to current session PATH if needed
if ($writablePathDir) {
    if ($env:PATH -notlike "*$writablePathDir*") {
        $env:PATH = "$writablePathDir;$env:PATH"
        Write-Host "  ✓ Added to current session PATH: $writablePathDir" -ForegroundColor Green
    }
} elseif ($launcherDirCreated) {
    $newLauncherDir = $PossibleLauncherDirs | Where-Object { Test-Path $_ } | Select-Object -First 1
    if ($newLauncherDir -and ($env:PATH -notlike "*$newLauncherDir*")) {
        $env:PATH = "$newLauncherDir;$env:PATH"
        Write-Host "  ✓ Added to current session PATH: $newLauncherDir" -ForegroundColor Green
    }
}

Write-Host ""

# Step 5: Verification
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "   Verification" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan

# Test if adp command works
$testAdp = Get-Command adp -ErrorAction SilentlyContinue
if ($testAdp) {
    Write-Host "✅ ADP CLI is available: $($testAdp.Source)" -ForegroundColor Green
    
    # Try to get version
    try {
        $version = & adp --version 2>&1
        Write-Host "✅ Version: $version" -ForegroundColor Green
    }
    catch {
        Write-Host "⚠️  Could not get version (may need new terminal)" -ForegroundColor Yellow
    }
} else {
    Write-Host "⚠️  ADP CLI not found in current session" -ForegroundColor Yellow
}

Write-Host ""

# Step 6: Final summary
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "   Installation Complete" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "📁 Installation location:" -ForegroundColor Cyan
Write-Host "   $AdpInstallDir" -ForegroundColor White
Write-Host ""
Write-Host "🔧 Launcher location:" -ForegroundColor Cyan
if ($writablePathDir) {
    Write-Host "   $writablePathDir\adp.bat" -ForegroundColor White
} elseif ($launcherDirCreated) {
    Write-Host "   $($PossibleLauncherDirs[0])\adp.bat" -ForegroundColor White
}
Write-Host ""
Write-Host "📌 Next steps:" -ForegroundColor Cyan
if (-not $testAdp) {
    Write-Host "   1. Close this terminal window" -ForegroundColor White
    Write-Host "   2. Open a NEW PowerShell or Command Prompt" -ForegroundColor White
    Write-Host "   3. Run 'adp --help' to verify installation" -ForegroundColor White
} else {
    Write-Host "   • Run 'adp --help' to get started" -ForegroundColor White
    Write-Host "   • Run 'adp config' to configure settings" -ForegroundColor White
}
Write-Host ""
Write-Host "💡 The ADP CLI is now permanently available in all terminals" -ForegroundColor Cyan
Write-Host "   without modifying system PATH!" -ForegroundColor Cyan